# Generated by Django 4.2.7 on 2023-11-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdu',
            name='fechayhora',
            field=models.DateTimeField(),
        ),
    ]
