# Generated by Django 4.2.7 on 2023-11-29 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_carrera_nombre_alter_facultad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.facultad'),
            preserve_default=False,
        ),
    ]
