# Generated by Django 4.2.7 on 2023-11-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_carrera_facultad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='facultad',
            new_name='id_facultad',
        ),
    ]
