# Generated by Django 4.2.7 on 2023-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_facultad_carrera_id_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
