# Generated by Django 4.2.7 on 2023-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_carrera_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='id_facultad',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
