# Generated by Django 4.2.7 on 2023-11-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_carrera_facultad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdu',
            name='id_facultad',
        ),
    ]
